owner: kreatoo
repo: status.krea.to

sites:
  - name: iris
    url: https://iris.krea.to
    expectedStatusCodes:
      - 404
  - name: lily
    url: https://lily.krea.to
    expectedStatusCodes:
      - 404
  - name: lb
    url: https://lb.krea.to
    expectedStatusCodes:
      - 404
  - name: MinIO
    url: https://s3.krea.to
    expectedStatusCodes:
      - 400
      - 403
  - name: binrepo
    url: https://bin.kreato.dev
  - name: koito
    url: https://fm.krea.to
  - name: mastodon
    url: https://m.kreato.dev
  - name: umami
    url: https://umami.krea.to/dashboard
  - name: n8n
    url: https://n8n.krea.to
  - name: mirror
    url: https://mirror.kreato.dev
  - name: main
    url: https://krea.to
  - name: helm
    url: https://helm.kreato.dev
  - name: llm
    url: https://llm.krea.to/v1/
    expectedStatusCodes:
      - 404
  - name: klinux
    url: https://linux.kreato.dev
  - name: media
    url: https://media.krea.to
  

status-website:
  cname: status.krea.to
  logoUrl: https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png
  name: krea.to Status
  themeUrl: https://status.krea.to/catppuccin-mocha.css
  introTitle: "**krea.to** Infrastructure Health Status"
  introMessage: Real-time monitoring of krea.to infrastructure health status, including internal and external services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kreatoo/bouquet2 
