owner: kreatoo
repo: status.krea.to

sites:
  - name: MinIO
    url: https://s3.krea.to
    expectedStatusCodes:
      - 400
      - 403
  - name: binrepo
    url: https://bin.krea.to
  - name: koito
    url: https://fm.krea.to
  - name: umami
    url: https://umami.krea.to/dashboard
  - name: mirror
    url: https://mirror.kreato.dev
  - name: main
    url: https://krea.to
  - name: klinux
    url: https://linux.krea.to  

status-website:
  cname: status.krea.to
  logoUrl: https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png
  name: krea.to Status
  themeUrl: https://status.krea.to/catppuccin-mocha.css
  introTitle: "**krea.to** Infrastructure Health Status"
  introMessage: Real-time monitoring of krea.to infrastructure health status, including internal and external services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kreatoo/bouquet2 
